name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on : ubuntu-latest
    steps:
      - name : Checkout Repository
        uses : actions/checkout@v4

      - name : Login to DockerHub
        uses : docker/login-action@v3
        with :
          username : ${{ secrets.DOCKERHUB_USERNAME }}
          password : ${{ secrets.DOCKERHUB_TOKEN }}
      

      - name : Build and push Docker Image
        uses : docker/build-push-action@v6
        with :
          context : .
          file : ./Dockerfile
          push : true
          tags : |
            ${{ secrets.DOCKERHUB_USERNAME}}/todo:latest
      
      - name : Deploy to EC2
        uses : appleboy/ssh-action@v1.2.0
        with : 
          host : ${{ secrets.EC2_HOST }}
          username : ${{ secrets.EC2_USER }}
          key : ${{ secrets.EC2_SSH_KEY }}
          port : 22
          script : |
            docker pull ${{ secrets.DOCKERHUB_USERNAME}}/todo:latest
            docker run -itd --network my-network --name todo-container -p 18888:8888 ${{ secrets.DOCKERHUB_USERNAME}}/todo:latest

          