name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on : ubuntu-latest
    steps:
      - name : Checkout Repository
        uses : actions/checkout@v4

      - name : Login to DockerHub
        uses : docker/login-action@v3
        with :
          username : ${{ secrets.DOCKERHUB_USERNAME }}
          password : ${{ secrets.DOCKERHUB_TOKEN }}
      

      - name : Build and push Docker Image
        uses : docker/build-push-action@v6
        with :
          context : .
          file : ./Dockerfile
          push : true
          tags : |
            ${{ secerets.DOCKERHUB_USERNAME}}/todo_app:latest